apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iris-rf
  namespace: knative-demo
spec:
  template:
    spec:
      containers:
        - name: iris-rf
          image: boxkey/iris-rf:beta
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_MODEL_NAME
              value: "Iris_Random_Forest"
            - name: MLFLOW_MODEL_VERSION
              value: "1"
            - name: MLFLOW_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow
                  key: mlflowuri
                  optional: false